config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :homes, only: [:show]

  resources :prelaunches do
    collection do
    end
  end

  resources :profils

  get 'dashboards/home'
  get 'dashboards/welcome' => 'dashboards#homenew'
  get 'dashboards/smartphone'
  get 'dashboards/reparer'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :smartphones

  get 'pages/about'
  get 'pages/contact'
  get 'pages/index'

  get 'friends' => 'prelaunches#friends'

  root 'prelaunches#new'

end

app/models/smartphone.rb
class Smartphone < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.gif"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/smartphones_controller.rb
class SmartphonesController < ApplicationController
  before_action :set_smartphone, only: [:show, :edit, :update, :destroy]

  # GET /smartphones
  # GET /smartphones.json
  def index
    @smartphones = Smartphone.all
  end

  # GET /smartphones/1
  # GET /smartphones/1.json
  def show
  end

  # GET /smartphones/new
  def new
    @smartphone = Smartphone.new
  end

  # GET /smartphones/1/edit
  def edit
  end

  # POST /smartphones
  # POST /smartphones.json
  def create
    @smartphone = Smartphone.new(smartphone_params)

    respond_to do |format|
      if @smartphone.save
        format.html { redirect_to @smartphone, notice: 'Smartphone was successfully created.' }
        format.json { render :show, status: :created, location: @smartphone }
      else
        format.html { render :new }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smartphones/1
  # PATCH/PUT /smartphones/1.json
  def update
    respond_to do |format|
      if @smartphone.update(smartphone_params)
        format.html { redirect_to @smartphone, notice: 'Smartphone was successfully updated.' }
        format.json { render :show, status: :ok, location: @smartphone }
      else
        format.html { render :edit }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smartphones/1
  # DELETE /smartphones/1.json
  def destroy
    @smartphone.destroy
    respond_to do |format|
      format.html { redirect_to smartphones_url, notice: 'Smartphone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smartphone
      @smartphone = Smartphone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smartphone_params
      params.require(:smartphone).permit(:marque, :modele, :image)
    end
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/views/smartphones/_form.html.erb
<%= form_for @smartphone, :html => { :multipart => true } do |f| %>
  <% if @smartphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smartphone.errors.count, "error") %> prohibited this smartphone from being saved:</h2>

      <ul>
      <% @smartphone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :marque %><br>
    <%= f.text_field :marque, class: "form-control", value: "Apple" %>
  </div>
  <div class="form-group">
    <%= f.label :modele %><br>
    <%= f.text_field :modele, class: "form-control" %>
  </div>
  <div class="">
    <%= f.file_field :image, class: "form-control" %>
  </div><br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/smartphones/edit.html.erb
<h1>Editing smartphone</h1>

<%= render 'form' %>

<%= link_to 'Show', @smartphone, class: "btn btn-link" %> |
<%= link_to 'Back', smartphones_path, class: "btn btn-link" %>

app/views/smartphones/index.html.erb
<h1>Listing smartphones</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Marque</th>
      <th>Modele</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @smartphones.each do |smartphone| %>
      <tr>
        <td><%= image_tag smartphone.image.url(:medium) %></td>
        <td><%= smartphone.marque %></td>
        <td><%= smartphone.modele %></td>
        <td><%= link_to 'Show', smartphone %></td>
        <td><%= link_to 'Edit', edit_smartphone_path(smartphone) %></td>
        <td><%= link_to 'Destroy', smartphone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Smartphone', new_smartphone_path %>

app/views/smartphones/new.html.erb
<h1>New smartphone</h1>

<%= render 'form' %>

<%= link_to 'Back', smartphones_path, class: "btn btn-link" %>

app/views/smartphones/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @smartphone.image.url(:medium) %>

<p>
  <strong>Marque:</strong>
  <%= @smartphone.marque %>
</p>

<p>
  <strong>Modele:</strong>
  <%= @smartphone.modele %>
</p>

<%= link_to 'Edit', edit_smartphone_path(@smartphone) %> |
<%= link_to 'Back', smartphones_path %>