config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :homes, only: [:show]

  resources :prelaunches do
    collection do
    end
  end

  resources :profils

  get 'dashboards/home'
  get 'dashboards/welcome' => 'dashboards#homenew'
  get 'dashboards/smartphone'
  get 'dashboards/reparer'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :smartphones

  get 'pages/about'
  get 'pages/contact'
  get 'pages/index'

  get 'friends' => 'prelaunches#friends'

  root 'prelaunches#new'

end

app/models/profil.rb
class Profil < ActiveRecord::Base
	belongs_to :user

	attr_accessor :stripe_card_token
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  before_action :set_profil, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]
  before_filter :check_user, only: [:edit, :update, :destroy, :show]

  respond_to :html

  def index
    if user_signed_in?
      redirect_to dashboards_home_path
    else
      @profils = Profil.all
      respond_with(@profils)
    end
  end

  def show
    respond_with(@profil)
  end

  def new
    if Profil.exists?(:user_id => current_user.id)
      redirect_to dashboards_home_path 
    else
      @smartphone = Smartphone.find(current_user.phoneid)
      @profil = Profil.new
      respond_with(@profil)
    end
    
  end

  def edit
    @profil = Profil.find_by(user_id: current_user.id)
  end

  def create
    @profil = Profil.new(profil_params)
    @profil.user_id = current_user.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    stripe_card_token = params[:stripe_card_token]

    begin
      customer = Stripe::Customer.create(
        :description => current_user.email,
        :plan => "switchiz",
        :source => stripe_card_token
        )
      @profil.stripe_customer_token = customer.id
      @profil.save
      redirect_to dashboards_home_path, :notice => "Votre inscription est bien validée"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

  end

  def update
    @profil.update(profil_params)
    # respond_with(@profil)
    redirect_to dashboards_home_path 
  end

  def destroy
    @profil.destroy
    respond_with(@profil)
  end

  private
    def set_profil
      @profil = Profil.find(params[:id])
    end

    def profil_params
      params.require(:profil).permit(:user_id, :smartphone_id, :couleur_id, :prenom, :nom, :adresse, :compl_adresse, :imei, :numtel, :stripe_customer_token)
    end

    def check_user
      if current_user != @profil.user
        redirect_to dashboards_home_path, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/views/profils/_form.html.erb
<%= form_for(@profil) do |f| %>
  <% if @profil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profil.errors.count, "error") %> prohibited this profil from being saved:</h2>

      <ul>
      <% @profil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :smartphone_id %><br>
    <%= f.hidden_field :smartphone_id, :id => 'profil_modele' %>
    <div class="col-md-12 dropdown">
      <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Sélectionnez votre smartphone
          <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <% Smartphone.where(marque: 'Apple').to_a.each do |smartphone| %>
          <li><a href="" onClick="return getmodele(<%= smartphone.id %>);"><%= smartphone.modele %></a></li>
        <% end %>
        <li class="divider"></li>
        <li><a href="" onClick="">Autre</a></li>
      </ul>
    </div>
  </div><br>
  <div class="field">
    <%= f.label :couleur_id %><br>
    <%= f.number_field :couleur_id %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse %>
  </div>
  <div class="field">
    <%= f.label :compl_adresse %><br>
    <%= f.text_field :compl_adresse %>
  </div>
  <div class="field">
    <%= f.label :imei %><br>
    <%= f.number_field :imei %>
  </div>
  <div class="field">
    <%= f.label :numtel %><br>
    <%= f.text_field :numtel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  function getmodele(modele) {
      document.getElementById('profil_modele').value = modele;
      return false;
  }
</script>

app/views/profils/_formadresse.html.erb
<%= form_for(@profil) do |f| %>
  <% if @profil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profil.errors.count, "error") %> prohibited this profil from being saved:</h2>

      <ul>
      <% @profil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="form-group col-md-6">
      <%= f.label :prenom %><br>
      <%= f.text_field :prenom, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :nom %><br>
      <%= f.text_field :nom, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label :adresse %><br>
      <%= f.text_field :adresse, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label "Complément d'adresse" %><br>
      <%= f.text_field :compl_adresse, class: "form-control", placeholder: "(Code d'accès, bâtiment, etc...)" %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label "Numéro de téléphone" %><br>
      <%= f.text_field :numtel, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <div>
<% end %>

<script type="text/javascript">
  function getmodele(modele) {
      document.getElementById('profil_modele').value = modele;
      return false;
  }
</script>

app/views/profils/_formfirst.html.erb
<%= form_for(@profil) do |f| %>
  <% if @profil.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h2><%= pluralize(@profil.errors.count, "error") %> prohibited this profil from being saved:</h2>

      <ul>
      <% @profil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-12">
    <div class="col-md-4">
      <div class="col-md-12 panel panel-default">
        <div class="text-center">
          <br>
          <%= image_tag @smartphone.image.url(:medium) %><br>
        </div>
        <h4>Votre abonnement Switchiz :</h4>
        <i class="fa fa-check" aria-hidden="true"></i> Réparations gratuites<br>
        <i class="fa fa-check" aria-hidden="true"></i> Assistance 7j/7<br>
        <i class="fa fa-check" aria-hidden="true"></i> Box Switchiz chaque mois<br>
        <i class="fa fa-check" aria-hidden="true"></i> Sans engagement<br>
        <h3>9,99€/mois</h3>
      </div>
    </div>



    <div class="col-md-8">
      <div class="col-md-12">
        <div class="col-md-4 text-center">
          <i class="fa fa-lock fa-2x" aria-hidden="true"></i><br>
          <h4>Paiement sécurisé</h4>
        </div>
        <div class="col-md-4 text-center">
          <i class="fa fa-undo fa-2x" aria-hidden="true"></i><br>
          <h4>14 jours pour changer d'avis</h4>
        </div>
        <div class="col-md-4 text-center">
          <i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i><br>
          <h4>Livraison offerte</h4>
        </div>
      </div><br>

      <div class="form-group">
        <%= f.label "Prénom*" %><br>
        <%= f.text_field :prenom, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= f.label "Nom*" %><br>
        <%= f.text_field :nom, class: "form-control", required: true %>
      </div>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Numéro de carte banquaire" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "card-number form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control card-cvc" } %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag nil, "Date d'expiration" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "card-expiry-month form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "card-expiry-year form-control" } %>
          </div>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "REJOINDRE LE CLUB", class: "btn btn-primary btn-block", data: { no_turbolink: true }%>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  function getmodele(idmodele) {
      document.getElementById('profil_modele').value = idmodele;
      $("a#dropdown_text").text("Modifier");
      return false;
  }
</script>

app/views/profils/_formimei.html.erb
<%= form_for(@profil) do |f| %>
  <% if @profil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profil.errors.count, "error") %> prohibited this profil from being saved:</h2>

      <ul>
      <% @profil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label "Votre numéro IMEI (15 chiffres)" %><br>
      <%= f.text_field :imei, class: "form-control", required: true %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/profils/edit.html.erb
<h1>Mon profil</h1>

<% if @profil.adresse == nil %>
	<%= render 'formadresse' %>
<% else  %>
	<%= render 'form' %>
<% end  %>

app/views/profils/index.html.erb
<h1>Listing profils</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Smartphone</th>
      <th>Couleur</th>
      <th>Prenom</th>
      <th>Nom</th>
      <th>Adresse</th>
      <th>Compl adresse</th>
      <th>Imei</th>
      <th>Numtel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profils.each do |profil| %>
      <tr>
        <td><%= profil.user_id %></td>
        <td><%= profil.smartphone_id %></td>
        <td><%= profil.couleur_id %></td>
        <td><%= profil.prenom %></td>
        <td><%= profil.nom %></td>
        <td><%= profil.adresse %></td>
        <td><%= profil.compl_adresse %></td>
        <td><%= profil.imei %></td>
        <td><%= profil.numtel %></td>
        <td><%= link_to 'Show', profil %></td>
        <td><%= link_to 'Edit', edit_profil_path(profil) %></td>
        <td><%= link_to 'Destroy', profil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profil', new_profil_path %>

app/views/profils/new.html.erb
<br>
<h1 class="text-center" >Bienvenue ! Vous faites presque partie du club :)</h1>
<br>

<%= render 'formfirst' %>

app/views/profils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @profil.user_id %>
</p>

<p>
  <strong>Smartphone:</strong>
  <%= @profil.smartphone_id %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= @profil.couleur_id %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @profil.prenom %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @profil.nom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @profil.adresse %>
</p>

<p>
  <strong>Compl adresse:</strong>
  <%= @profil.compl_adresse %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @profil.imei %>
</p>

<p>
  <strong>Numtel:</strong>
  <%= @profil.numtel %>
</p>

<%= link_to 'Edit', edit_profil_path(@profil) %> |
<%= link_to 'Back', profils_path %>