config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :homes, only: [:show]

  resources :prelaunches do
    collection do
    end
  end

  resources :profils

  get 'dashboards/home'
  get 'dashboards/welcome' => 'dashboards#homenew'
  get 'dashboards/smartphone'
  get 'dashboards/reparer'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :smartphones

  get 'pages/about'
  get 'pages/contact'
  get 'pages/index'

  get 'friends' => 'prelaunches#friends'

  root 'prelaunches#new'

end

app/models/prelaunch.rb
class Prelaunch < ActiveRecord::Base

	validates_format_of :email, :with => /@/
	
end

app/controllers/prelaunches_controller.rb
class PrelaunchesController < ApplicationController
  before_action :set_prelaunch, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:index, :edit, :update, :destroy, :show]

  respond_to :html

  def index
    @prelaunches = Prelaunch.all
    @prelaunchescount = 0
    @prelaunchesref = 0
    @prelaunches.each do |prelaunch|
      @prelaunchescount = @prelaunchescount +1
      if prelaunch.ref.blank?
      else
        @prelaunchesref = @prelaunchesref +1
      end
    end

    @ratio = @prelaunchesref.to_i / @prelaunchescount.to_f
    # @prelaunchesref = @prelaunches.count - @prelaunchesnoref 
    respond_with(@prelaunches)
    # redirect_to root_path
  end

  def show
    respond_with(@prelaunch)
  end

  def friends
    @code = params[:code]
    @codefb = "ref="+@code
    @aventurier = Prelaunch.find_by(code: @code)

    if Prelaunch.exists?(code: @code)
    else
      redirect_to root_path, alert: "Votre email est invalide"
    end
    
    # @prelaunch = Prelaunch.find_by(@id)
    # @ref = @prelaunch.code
  end

  def new
    @n = params[:n]
    @inv = params[:inv]
    @cookee = cookies[:refcode]
    if @inv.blank?
    else
      @aventurier = Prelaunch.find_by(code: @inv)
      @comment = @aventurier.commentaire
    end
    @prelaunch = Prelaunch.new
    respond_with(@prelaunch)
  end

  def edit
  end

  def create
    @prelaunch = Prelaunch.new(prelaunch_params)

      if @prelaunch.ref == "" || @prelaunch.ref == nil
        @prelaunch.code = SecureRandom.hex(4) # => "bff1a1a2"
        @prelaunch.count = 0
      else
        if Prelaunch.exists?(code: @prelaunch.ref)
          @referral = Prelaunch.find_by(code: @prelaunch.ref)
          @referral.update(:count => @referral.count+1)
          @prelaunch.code = SecureRandom.hex(4) # => "bff1a1a2"
        end
        @prelaunch.code = SecureRandom.hex(4)
        @prelaunch.count = 0
      end
    
    @prelaunch.save
    cookies[:refcode] = { value: @prelaunch.code, expires: 1.month.from_now }
    # respond_with(@prelaunch)
    redirect_to action: 'friends', code: @prelaunch.code
    
  end

  def update
    @prelaunch.update(prelaunch_params)
    respond_with(@prelaunch)
  end

  def destroy
    @prelaunch.destroy
    respond_with(@prelaunch)
  end

  private
    def set_prelaunch
      @prelaunch = Prelaunch.find(params[:id])
    end

    def prelaunch_params
      params.require(:prelaunch).permit(:email, :commentaire, :count, :code, :ref)
    end
end

app/helpers/prelaunches_helper.rb
module PrelaunchesHelper
end

app/views/prelaunches/_form.html.erb
<%= form_for(@prelaunch) do |f| %>
  <% if @prelaunch.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>Votre email n'est pas valide</h4>
    </div>
  <% end %>
  <%= f.hidden_field :ref, :value => @inv %>
  <%= f.hidden_field :commentaire, :value => @n %>
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="form-group col-md-7">
      <%= f.email_field :email, class: "form-control champ", placeholder: "Entre ton email", required: true %>
    </div>
    <div class="actions col-md-5">
      <%= f.submit "Rejoindre l'aventure !", class: "btn btn-primary btn-block" %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert" style="color:red;"><%= alert %></p>
  </div>
  <div class="col-md-3"></div>
<% end %>

app/views/prelaunches/_modalform.html.erb
<%= form_for(@prelaunch) do |f| %>
  <% if @prelaunch.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>Votre email n'est pas valide</h4>
    </div>
  <% end %>
  <%= f.hidden_field :ref, :value => @inv %>
  <div class=""></div>
  <div class="">
    <div class="form-group">
      <%= f.email_field :email, class: "form-control email", placeholder: "Entre ton email", required: true, :onkeyup => "funct()" %>
    </div>

    <div class="actions">
      <%= f.submit "D'accord, j'ai craqué", class: "btn btn-danger btn-block" %>
    </div>
  </div>
  <div class="col-md-3"></div>
<% end %>

app/views/prelaunches/_modalone.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Tu nous quittes déjà <%= @n %> ?</h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <%= image_tag("chatpotte.gif", width: '300') %><br><br>
          Pourtant on fait tout ça avec amour <3 <br><br>
          <%= render 'modalform' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prelaunches/_modaltwo.html.erb
<!-- Modal -->
<div class="modal fade" id="myModaltwo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Il suffit d'un clic</h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <%= image_tag("kanye.gif", width: '400', height: '262') %><br><br>
          Soit l'ami qui fait découvrir les trucs cools ;) <br><br>
          <iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2Fswitchiz.co%2F?inv=<%= @code %>&layout=button&size=large&mobile_iframe=false&appId=1883784975182089&width=90&height=28&locale=fr_FR" width="90" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

          <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-text="Switchiz arrive bientôt et j&#39;ai pris ma place aux 1ères loges ! Qui me suit ?" data-url="http://switchiz.co/?inv=<%= @code %>" data-hashtags="ChouchouteurDeSmartphones" data-lang="fr" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prelaunches/edit.html.erb
<h1>Editing prelaunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @prelaunch %> |
<%= link_to 'Back', prelaunches_path %>

app/views/prelaunches/friends.html.erb
<!-- Header -->
<header id="" class="header-partage">
    <div class="container text-center">
        <div class="container text-center">
            <%= image_tag "logo.png", :class => "logo-prelaunch-bis", :size => "125x88" %>
        </div><br>
        <div class="col-md-3"></div>
        <div class="header-partage-text col-md-6" style="background-color: rgba(0,0,0,0.4); padding: 0px 20px 20px 15px; border-radius: 10px; display:block;">
            <h3 class="header-first-text">L'abonnement Switchiz te permet de recevoir des accessoires cools et de faire réparer ton smartphone gratuitement</h3>
            <h1 class="header-next-text">INVITE TES AMIS ET GAGNE UN ESSAI GRATUIT À SWITCHIZ !</h1>
            Partage ton lien d'invitation sur Facebook, Twitter ou par mail et gagne un accès privé pour tester Switchiz<br><br>

            <iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2Fswitchiz.co%2F?inv=<%= @code %>&layout=button&size=large&mobile_iframe=false&appId=1883784975182089&width=90&height=28&locale=fr_FR" width="90" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

            <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-text="Switchiz arrive bientôt et j&#39;ai pris ma place aux 1ères loges ! Qui me suit ?" data-url="http://switchiz.co/?inv=<%= @code %>" data-hashtags="ChouchouteurDeSmartphones" data-lang="fr" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script><br><br>

            <input readonly class="form-control champ-partage" value="http://switchiz.co/?inv=<%= @code %>">
        </div>
        <div class="col-md-3"></div>
    </div>
</header>

<section class="section-landing">
    <div class=container>
        <h3>Comment ça marche ?</h3>
        <div class="col-md-4" style="color: #52a7bf"><strong><br>Amis inscrits : <%= @aventurier.count %> <br> (Vous n'avez aucun ami inscrit pour le moment)</strong></div>
        <div class="col-md-2"><br><span style="color: #52a7bf" >5 amis inscrits </span><br> = <br>1 Accessoire Switchiz Offert<br></div>
        <div class="col-md-2"><br><span style="color: #52a7bf" >10 amis inscrits </span><br> = <br>1 Mois d'Entretien Switchiz Offert<br></div>
        <div class="col-md-2"><br><span style="color: #52a7bf" >25 amis inscrits </span><br> = <br>6 Mois d'Entretien Switchiz Offert<br></div>
        <div class="col-md-2"><br><span style="color: #52a7bf" >50 amis inscrits </span><br> = <br>1 An d'Entretien Switchiz Offert<br></div>
        <div class="giftbar col-md-12"></div>
        <div class="col-md-12"></div>
    </div>
</section>

<%= render 'modaltwo' %>

<script type="text/javascript">

    mixpanel.track("Prelaunch sharepage");
	
	function addEvent(obj, evt, fn) {
    if (obj.addEventListener) {
        obj.addEventListener(evt, fn, false);
    }
    else if (obj.attachEvent) {
        obj.attachEvent("on" + evt, fn);
    }
}

addEvent(document, 'mouseout', function(evt) {
    if (evt.toElement == null && evt.relatedTarget == null) {
        $('#myModaltwo').modal('show');
    }
});
</script>

app/views/prelaunches/index.html.erb
<h1>Listing prelaunches</h1>

<h3> Nombre de leads = <strong><%= @prelaunchescount %></strong></h3>
<h3> Nombre de referrals = <strong><%= @prelaunchesref %></strong></h3>
<h3> Indice de viralité = <strong><%= @ratio %></strong> (doit être supérieur à 1 pour devenir viral)</h3>

<br><br>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Commentaire</th>
      <th>Count</th>
      <th>Code</th>
      <th>Ref</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prelaunches.order(count: :desc).each do |prelaunch| %>
      <tr>
        <td><%= prelaunch.id %></td>
        <td><%= prelaunch.email %></td>
        <td><%= prelaunch.commentaire %></td>
        <td><%= prelaunch.count %></td>
        <td><%= prelaunch.code %></td>
        <td><%= prelaunch.ref %></td>
        <td><%= link_to 'Show', prelaunch %></td>
        <td><%= link_to 'Edit', edit_prelaunch_path(prelaunch) %></td>
        <td><%= link_to 'Destroy', prelaunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prelaunch', new_prelaunch_path %>

app/views/prelaunches/new.html.erb
<!-- Header -->
<header id="" class="header-landing">
    <div class="container text-center">
    	<div class="container text-center">
    		<%= image_tag "logo.png", :class => "logo-prelaunch", :size => "175x123" %>
		</div>
    	<div class="header-landing-text">
    		<% if @n.blank? %>
    			<% if @inv.blank? %>
    				<h1 class="header-first-text">L'aventure Switchiz commence bientôt</h1>
    			<% else %>
                    <% if @comment.blank? %>
                        <h1 class="header-first-text">L'aventure Switchiz commence bientôt</h1>
                    <% else %>
    				    <h1 class="header-first-text"><%= @comment %> t'invite à découvrir Switchiz</h1>
                    <% end %>
    			<% end %>
    		<% else %>
    			<h1 class="header-first-text">Hello <%= @n %></h1>
    		<% end %>
    		
            <h2 class="header-next-text">L'entretien de smartphone, réinventé !</h2>
    	</div>
	</div>
</header>

<section class="section-landing">
	<h3><i class="fa fa-lock fa-1x" aria-hidden="true"></i><br>Rejoins le club qui va chouchouter ton smartphone ;) <br> Fais partie des premiers au courant ! </h3>
    <% if @cookee.blank? %>
        <%= render 'form' %>
    <% else %>
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <%= link_to "Voir mes amis inscrits", friends_path(:code => @cookee), :class => "btn btn-primary" %><br>
        </div>
        <div  class="col-md-4"></div>
    <% end %>
	

	<div class="col-md-12 text-center prelaunch-footer">
		<p><a href="mailto:gwenael@switchiz.co">gwenael@switchiz.co</a></p>
	</div>
</section>

<%= render 'modalone' %>
<script type="text/javascript">
	
	mixpanel.track("Prelaunch homepage");

	function addEvent(obj, evt, fn) {
    if (obj.addEventListener) {
        obj.addEventListener(evt, fn, false);
    }
    else if (obj.attachEvent) {
        obj.attachEvent("on" + evt, fn);
    }
}

addEvent(document, 'mouseout', function(evt) {
    if (evt.toElement == null && evt.relatedTarget == null) {
        $('#myModal').modal('show');
    }
});

</script>

app/views/prelaunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @prelaunch.email %>
</p>

<p>
  <strong>Commentaire:</strong>
  <%= @prelaunch.commentaire %>
</p>

<p>
  <strong>Count:</strong>
  <%= @prelaunch.count %>
</p>

<p>
  <strong>Code:</strong>
  <%= @prelaunch.code %>
</p>

<p>
  <strong>Ref:</strong>
  <%= @prelaunch.ref %>
</p>

<%= link_to 'Edit', edit_prelaunch_path(@prelaunch) %> |
<%= link_to 'Back', prelaunches_path %>