config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :homes, only: [:show]

  resources :prelaunches do
    collection do
    end
  end

  resources :profils

  get 'dashboards/home'
  get 'dashboards/welcome' => 'dashboards#homenew'
  get 'dashboards/smartphone'
  get 'dashboards/reparer'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :smartphones

  get 'pages/about'
  get 'pages/contact'
  get 'pages/index'

  get 'friends' => 'prelaunches#friends'

  root 'prelaunches#new'

end

app/views/layouts/_footer.html.erb
<nav id="footer">
    <div class="container">
        <div class="pull-left fnav">
            <p>ALL RIGHTS RESERVED. COPYRIGHT © 2016</p>
        </div>
        <div class="pull-right fnav">
            <ul class="footer-social">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_header.html.erb
<!-- Navigation
    ==========================================-->
    <nav id="tf-menu" class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? %>
                <%= link_to "Switchiz", dashboards_home_path, :class => "navbar-brand" %>
            <% else %>
                <%= link_to "Switchiz", root_path, :class => "navbar-brand" %>
            <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="#tf-home" class="page-scroll">Accueil</a></li>
            <li><a href="#tf-about" class="page-scroll">Le Club</a></li> -->
            <li><a href="#tf-team" class="page-scroll">Le Club</a></li>
            <li><a href="#tf-services" class="page-scroll">Réparations</a></li>
            <li><a href="#tf-works" class="page-scroll">Les Boxs</a></li>
            <li><a href="#tf-testimonials" class="page-scroll">Comment ça marche ?</a></li>
            <!-- <li><a href="#tf-contact" class="page-scroll">Contact</a></li> -->
            <% if user_signed_in? %>
                    <li class="active"><a href="#">Réparer mon smartphone</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Mon Compte</a></li>
                          <li class="divider"></li>
                          <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Se connecter", root_path %></li>
                <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Switchiz - L'aventure commence bientôt !</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>

  <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">

  <meta name="description" content="Switchiz prend soin de vous et de votre smartphone !">
  <meta name="author" content="Switchiz">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

  <meta property="fb:app_id" content="1883784975182089" /> 
  <meta property="og:title" content="L'aventure Switchiz Commence Bientôt !" />
  <meta property="og:site_name" content="Switchiz"/>
  <meta property="og:url" content="http://www.switchiz.co" />
  <meta property="og:description" content="Rejoignez le club qui va chouchouter votre smartphone !"/>
  <meta property="og:image" content="http://www.switchiz.co/assets/switchiz-fb-prop.jpg" />
  <meta property="og:image:type" content="image/jpeg" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@heyswitchiz" />
  <meta name="twitter:title" content="L'aventure Switchiz Commence Bientôt !" />
  <meta name="twitter:description" content="Rejoignez le club qui va chouchouter votre smartphone !" />
  <meta name="twitter:image" content="http://www.switchiz.co/assets/switchiz-fb-prop.jpg" />

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

  <!-- Slider
    ================================================== -->
    <%= stylesheet_link_tag "owl.carousel", media: "screen" %>
    <%= stylesheet_link_tag "owl.theme", media: "screen" %>

  
  <%= javascript_include_tag "modernizr.custom" %>
  
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
    0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
    for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
    mixpanel.init("431fcdac65a255659d4e311ddd16d836");</script><!-- end Mixpanel -->
</head>
<body>
  <% if current_page?(root_path) || current_page?(friends_path) %>
  <% else %>
    <%= render 'layouts/header' %>
  <% end %>
	
  <% if current_page?(root_path) || current_page?(friends_path) || current_page?(pages_index_path)%>
    <div class="">
  <% else %>
    <div class="container">
		  <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
		<%= yield %>
	</div>

  <% if current_page?(root_path) || current_page?(friends_path) %>
  <% else %>
    <%= render'layouts/footer' %>
  <% end %>
</body>
</html>